# Generated by Django 4.0.4 on 2022-06-27 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
